import asyncio
from typing import List
# Assuming autogen_feature_generator is in the same directory orPYTHONPATH is set
from .autogen_feature_generator import run_autogen_feature_description

def get_features_via_autogen(prompt: str, n: int) -> List[str]:
    """
    Calls the Autogen agent `n` times sequentially (synchronously) 
    to generate feature descriptions.

    Args:
        prompt: The prompt string generated by NLAgent.
        n: The number of feature descriptions to generate.

    Returns:
        A list of `n` raw string responses from the Autogen agent.
        May contain empty strings if some agent runs fail.
    """
    if n <= 0:
        return []

    final_responses = []
    print(f"Running Autogen sequentially {n} times...") # Info message
    for i in range(n):
        print(f"Autogen run {i+1}/{n}...") # Progress info
        # Call the now synchronous function directly
        result = run_autogen_feature_description(prompt)
        final_responses.append(result)
        
    print("Autogen sequential runs complete.") # Completion message
    return final_responses

# Example of how NLAgent might call this (for illustration)
def example_usage(): # Changed to synchronous example
    test_prompt = """/* Data description: Example Data */
Generate a new feature for predicting 'target'. Model: 'XGBoost'.
Output format:
'new_feature': '...',
'detailed description': '...',
'brief description': '...',
'relevant': ['...']
"""
    num_features_to_generate = 3
    print(f"Requesting {num_features_to_generate} features via Autogen (sequentially)...")
    responses = get_features_via_autogen(test_prompt, n=num_features_to_generate)
    print("\n--- Received Responses --- ")
    for i, resp in enumerate(responses):
        print(f"Response {i+1}:\n{resp}\n---")

if __name__ == "__main__":
    # example_usage() # Run synchronous example directly
    pass 